// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqvN4ugsS6cerpD0r_Uxg2ZtM-2eugIpI',
    appId: '1:442985931315:web:8d627504322cbab70a7946',
    messagingSenderId: '442985931315',
    projectId: 'reminder-fe024',
    authDomain: 'reminder-fe024.firebaseapp.com',
    storageBucket: 'reminder-fe024.firebasestorage.app',
    measurementId: 'G-RMEQRVKES7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCevRYM7a_cwHFFIlj-OTjOmcYHnrhOT2c',
    appId: '1:442985931315:android:4faadbbb3ce6f8e60a7946',
    messagingSenderId: '442985931315',
    projectId: 'reminder-fe024',
    storageBucket: 'reminder-fe024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtHhgXgIrCgTOGbbj56_Xkt94_bOr9qKc',
    appId: '1:442985931315:ios:6fe05b9d297c37300a7946',
    messagingSenderId: '442985931315',
    projectId: 'reminder-fe024',
    storageBucket: 'reminder-fe024.firebasestorage.app',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtHhgXgIrCgTOGbbj56_Xkt94_bOr9qKc',
    appId: '1:442985931315:ios:6fe05b9d297c37300a7946',
    messagingSenderId: '442985931315',
    projectId: 'reminder-fe024',
    storageBucket: 'reminder-fe024.firebasestorage.app',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqvN4ugsS6cerpD0r_Uxg2ZtM-2eugIpI',
    appId: '1:442985931315:web:d1592f5e7e6dd9170a7946',
    messagingSenderId: '442985931315',
    projectId: 'reminder-fe024',
    authDomain: 'reminder-fe024.firebaseapp.com',
    storageBucket: 'reminder-fe024.firebasestorage.app',
    measurementId: 'G-SSYEC3SM8K',
  );

}